import { Language } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    title: 'PLANET DEFENSE',
    start: 'START GAME',
    restart: 'PLAY AGAIN',
    gameOver: 'GAME OVER',
    victory: 'VICTORY!',
    score: 'SCORE',
    target: 'TARGET',
    wave: 'WAVE',
    paused: 'PAUSED',
    resume: 'RESUME',
    quit: 'QUIT',
    ammo: 'AMMO',
    lostMsg: 'All defenses have fallen.',
    winMsg: 'The sector is secure.',
    tutorialTitle: 'MISSION BRIEFING',
    tutorialStep1: 'Tap screen to intercept enemy rockets.',
    tutorialStep2: 'Protect cities and batteries at the bottom.',
    tutorialStep3: 'Middle battery features scatter-shot tech.',
    tutorialStep4: 'Right-click to activate Gravity Well.',
    tutorialStep5: 'Hold [S] + Click building for Shield.',
    tutorialStep6: 'Boss: Shield vs Laser -> Gravity on Dish -> Fire!',
    controlsHint: 'Controls: Left Click - Fire | Right Click - Gravity Well | [S] + Click - Shield',
    tutorialGotIt: 'UNDERSTOOD',
  },
  [Language.CN]: {
    title: '行星防御',
    start: '开始游戏',
    restart: '再玩一次',
    gameOver: '游戏结束',
    victory: '胜利！',
    score: '分数',
    target: '目标',
    wave: '波次',
    paused: '已暂停',
    resume: '继续',
    quit: '退出',
    ammo: '弹药',
    lostMsg: '所有防御工事已被摧毁。',
    winMsg: '该星区已安全。',
    tutorialTitle: '作战简报',
    tutorialStep1: '点击屏幕拦截敌方导弹。',
    tutorialStep2: '保护底部的城市和炮台。',
    tutorialStep3: '中间炮台拥有散射技术。',
    tutorialStep4: '右键点击激活引力场。',
    tutorialStep5: '按住 [S] + 点击建筑开启护盾。',
    tutorialStep6: 'BOSS战：护盾挡激光 -> 引力波吸弱点 -> 开火！',
    controlsHint: '操作：左键 - 开火 | 右键 - 引力场 | [S] + 点击 - 护盾',
    tutorialGotIt: '进入战场',
  },
};
